export type { DotContentPrimitive, DotContent, ISignal } from "./dot/content";
export type { IDotDocument, IDotConditionalDocument } from "./dot/i-dot-document";
export type {
	ComponentArgs,
	IDotCore,
	IDotWindowWrapper,
	IDotWindowBuilder,
} from "./dot/i-dot-core";
export type {
	IDotGlobalAttrs,
	IDotA,
	IDotArea,
	IDotAudio,
	IDotBlockQuote,
	IDotBody,
	IDotBr,
	IDotButton,
	IDotCanvas,
	IDotCol,
	IDotColGroup,
	IDotDel,
	IDotDetails,
	IDotEmbed,
	IDotFieldSet,
	IDotForm,
	IDotHr,
	IDotIFrame,
	IDotImg,
	IDotInput,
	IDotIns,
	IDotKeyGen,
	IDotLabel,
	IDotLi,
	IDotMap,
	IDotMenu,
	IDotMeter,
	IDotObject,
	IDotOl,
	IDotOptGroup,
	IDotOption,
	IDotOutput,
	IDotParam,
	IDotProgress,
	IDotQ,
	IDotSelect,
	IDotSource,
	IDotTable,
	IDotTextArea,
	IDotTBody,
	IDotTd,
	IDotTFoot,
	IDotTime,
	IDotTh,
	IDotTHead,
	IDotTr,
	IDotTrack,
	IDotVideo,
} from "./dot/i-dot-attrs";
